import test from 'node:test';
import assert from 'node:assert/strict';
import {createExecutionPreview} from '../lib/execution-preview.ts';
import {applyContextSelection,contextMessages,assertSelectionCompatible} from '../lib/context.mjs';
const memory={id:'memory-1',scopeId:'business',title:'Reviewed criterion',content:'PRIVATE_MEMORY',version:1,status:'confirmed',sharedWith:[],agentIds:[]};
const source={id:'source-1',scopeId:'business',title:'Reference document',version:1,digest:'digest',status:'current'};
function fixture(){
  let now=1000,remaining=5,calls=0,model='model-a';
  const context={scope:{id:'business'},memories:[memory],sources:[source],passages:[{sourceId:source.id,text:'PRIVATE_DOCUMENT'}]};
  const previews=createExecutionPreview({now:()=>now,prepare:{task:async input=>{calls++;return {kind:'task',id:input.id,version:1,title:'Work',scopeId:'business',selection:input.selection||{},steps:[{agentId:'forge',availableContext:context,context:applyContextSelection(context,input.selection),connection:{id:'provider',name:'Provider',model}}]};}},budget:async()=>({allowed:remaining>=1,remaining})});
  return {previews,input:{kind:'task',id:'task-1'},calls:()=>calls,advance:()=>now+=600001,budget:value=>remaining=value,model:value=>model=value};
}
test('preview displays exact selection and provenance; receipt is target bound and single use',async()=>{const f=fixture(),value=await f.previews.preview({...f.input,selection:{excludeMemoryIds:[memory.id],excludeSourceIds:[source.id]}});assert.equal(value.steps[0].memories[0].included,false);assert.equal(value.steps[0].sources[0].included,false);assert.equal(value.steps[0].sources[0].passages[0].text,'PRIVATE_DOCUMENT');await assert.rejects(f.previews.consume(value.previewId,{kind:'task',id:'task-2'}),{statusCode:409});const plan=await f.previews.consume(value.previewId,f.input);assert.deepEqual(plan.steps[0].context.memories,[]);assert.deepEqual(plan.steps[0].context.passages,[]);await assert.rejects(f.previews.consume(value.previewId,f.input),{statusCode:409});assert.equal(f.calls(),2);});
test('changed service or budget and expired receipts never authorize an old preview',async()=>{for(const mutate of [f=>f.model('model-b'),f=>f.budget(4),f=>f.advance()]){const f=fixture(),value=await f.previews.preview(f.input);mutate(f);await assert.rejects(f.previews.consume(value.previewId,f.input),{statusCode:409});}const f=fixture();f.budget(0);const value=await f.previews.preview(f.input);assert.equal(value.budget.allowed,false);await assert.rejects(f.previews.consume(value.previewId,f.input),{statusCode:409});});
test('excluded reference data cannot return through derived conversation messages or inherited task evidence',()=>{const snapshot={memories:[memory],workflows:[],sources:[source]},messages=[{role:'user',text:'Own request'},{role:'assistant',text:'PRIVATE_MEMORY',context:{memories:[memory]}},{role:'assistant',text:'PRIVATE_DOCUMENT',context:{sources:[source]}}];const selection={excludeMemoryIds:[memory.id],excludeSourceIds:[source.id]};assert.deepEqual(contextMessages(messages,{scopeId:'business',agentId:'forge',snapshot,selection}),[messages[0]]);assert.deepEqual(contextMessages(messages,{scopeId:'business',agentId:'forge',snapshot,selection:{includeHistory:false}}),[]);assert.throws(()=>assertSelectionCompatible({memories:[memory]},selection),{statusCode:409});assert.throws(()=>assertSelectionCompatible({sources:[source]},selection),{statusCode:409});assert.throws(()=>applyContextSelection({memories:[]},{excludeMemoryIds:['../../private']}),{statusCode:400});});
test('concurrent consumers cannot reuse one preview receipt',async()=>{const f=fixture(),value=await f.previews.preview(f.input);const results=await Promise.allSettled([f.previews.consume(value.previewId,f.input),f.previews.consume(value.previewId,f.input)]);assert.equal(results.filter(result=>result.status==='fulfilled').length,1);assert.equal(results.filter(result=>result.status==='rejected').length,1);assert.equal(f.calls(),2);await assert.rejects(f.previews.preview(null),{statusCode:400});});
