import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createWorkflowLearning} from '../lib/workflow-learning.ts';
import {createWorkspaceStore} from '../lib/workspace.mjs';
import {prepareWorkflowTask,starterWorkflowFields} from '../lib/workflow-inputs.mjs';
async function fixture(t){const directory=await mkdtemp(join(tmpdir(),'fuori-learning-'));t.after(()=>rm(directory,{recursive:true,force:true}));const workspace=createWorkspaceStore({directory});const task={id:'task-approved',version:4,scopeId:'business',title:'Reusable acceptance review',brief:'Use the supplied specification.',status:'completed',steps:[{title:'Review',agentId:'forge',instruction:'Check each acceptance criterion.',output:'PRIVATE_MODEL_OUTPUT'}],artifacts:[{version:2,decision:'approved',content:'PRIVATE_FINAL_DELIVERY',context:{memories:[],workflows:[],sources:[]}}]};let sourceChecks=0;const learner=createWorkflowLearning({workspace,operations:{getSnapshot:async()=>({tasks:[task]})},checkSources:async()=>{sourceChecks++;}});const input={taskId:task.id,expectedVersion:task.version};return{workspace,task,learner,input,sourceChecks:()=>sourceChecks};}
test('approved recipe previews without outputs or persistence and saves in its original scope with provenance',async t=>{const f=await fixture(t),before=await f.workspace.getSnapshot();const preview=await f.learner.preview(f.input);assert.equal(preview.workflow.steps[0].output,f.task.steps[0].instruction);assert.equal(JSON.stringify(preview).includes('PRIVATE_'),false);assert.deepEqual((await f.workspace.getSnapshot()).workflows,before.workflows);const {scopeId,source,sharedWith,...workflow}=preview.workflow;const saved=await f.learner.save({...f.input,workflow:{...workflow,status:'ready'}});const record=saved.snapshot.workflows.find(item=>item.id===saved.workflowId);assert.equal(record.scopeId,'business');assert.equal(record.status,'ready');assert.deepEqual(record.sharedWith,[]);assert.match(record.source,/delivery v2.*task-approved/);assert.equal(f.sourceChecks(),2);});
test('stale approval, unapproved latest version and forged scope/sharing fields cannot produce a recipe',async t=>{const f=await fixture(t);await assert.rejects(f.learner.preview({...f.input,expectedVersion:3}),{statusCode:409});f.task.status='review';await assert.rejects(f.learner.preview(f.input),{statusCode:409});f.task.status='completed';f.task.artifacts.at(-1).decision='pending';await assert.rejects(f.learner.preview(f.input),{statusCode:409});f.task.artifacts.at(-1).decision='approved';const p=await f.learner.preview(f.input);await assert.rejects(f.learner.save({...f.input,workflow:p.workflow}),{statusCode:400});await assert.rejects(f.learner.preview({...f.input,scopeId:'shared'}),{statusCode:400});});
test('restricted or revised memories block automatic derivation instead of broadening agent access',async t=>{const f=await fixture(t);const snapshot=await f.workspace.mutate('saveMemory',{scopeId:'business',title:'Restricted',content:'Private context',type:'fact',status:'confirmed',source:'fixture',sharedWith:[],agentIds:['forge']});const memory=snapshot.memories.at(-1);f.task.artifacts[0].context.memories=[{id:memory.id,version:memory.version}];await assert.rejects(f.learner.preview(f.input),{statusCode:409});await f.workspace.mutate('saveMemory',{...Object.fromEntries(['scopeId','title','content','type','status','source','sharedWith','agentIds'].map(k=>[k,memory[k]])),id:memory.id,expectedVersion:memory.version,agentIds:[]});await assert.rejects(f.learner.preview(f.input),{statusCode:409});});
test('long source instructions are explicitly marked as shortened and approval is rechecked when saving',async t=>{const f=await fixture(t);f.task.brief='b'.repeat(5000);f.task.steps[0].instruction='i'.repeat(2500);const p=await f.learner.preview(f.input);assert.equal(p.workflow.input.length,4000);assert.equal(p.workflow.steps[0].output.length,2000);assert.deepEqual(p.truncated,['input','steps.0.output']);const {scopeId,source,sharedWith,...workflow}=p.workflow;f.task.version++;await assert.rejects(f.learner.save({...f.input,workflow}),{statusCode:409});});
test('learning a fielded task restores the authorized template and clears case-specific values and defaults',async t=>{
  const f=await fixture(t);
  const fields=starterWorkflowFields().map(field=>({...field,defaultValue:field.key==='materials'?'PRIVATE_DEFAULT_MATERIAL':''}));
  const source=(await f.workspace.mutate('saveWorkflow',{scopeId:'business',title:'Reusable source',input:'Review {{materials}}.',output:'Deliver {{deliverable}}.',steps:[{title:'Review',agentId:'forge',output:'Evaluate {{objective}} within {{constraints}}.'}],status:'ready',inputFields:fields})).workflows.at(-1);
  Object.assign(f.task,{workflowId:source.id,...prepareWorkflowTask(source,{brief:'PRIVATE_CASE_BRIEF',inputValues:{objective:'PRIVATE_CASE_OBJECTIVE',deliverable:'PRIVATE_CASE_OUTPUT'},expectedWorkflowVersion:source.version})});
  f.task.artifacts[0].context.workflows=[{id:source.id,version:source.version}];
  const preview=await f.learner.preview(f.input);
  assert.equal(preview.workflow.input,source.input);assert.equal(preview.workflow.output,source.output);assert.deepEqual(preview.workflow.steps,source.steps);
  assert.deepEqual(preview.workflow.inputFields,fields.map(field=>({...field,defaultValue:''})));
  assert.equal(JSON.stringify(preview.workflow).includes('PRIVATE_'),false);
  await f.workspace.mutate('saveWorkflow',{id:source.id,expectedVersion:source.version,description:'Changed source'});
  await assert.rejects(f.learner.preview(f.input),{statusCode:409});
});
